// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhOooPHgKCZVocib9cGZnZtUC0mLQS4w',
    appId: '1:891507571778:web:b2390f27eb691dff3401db',
    messagingSenderId: '891507571778',
    projectId: 'seahawk-explorer',
    authDomain: 'seahawk-explorer.firebaseapp.com',
    storageBucket: 'seahawk-explorer.appspot.com',
    measurementId: 'G-WRMLQR5347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExeDhXg-ZNFxRqGCiluHhIDrANYqwPfE',
    appId: '1:891507571778:android:2a32fc553645d2ae3401db',
    messagingSenderId: '891507571778',
    projectId: 'seahawk-explorer',
    storageBucket: 'seahawk-explorer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXbw8jcMQrFQ2IZOqZLqSrEfcGgJ8Isp0',
    appId: '1:891507571778:ios:9bdba644eb6c435b3401db',
    messagingSenderId: '891507571778',
    projectId: 'seahawk-explorer',
    storageBucket: 'seahawk-explorer.appspot.com',
    iosBundleId: 'com.example.mbenton.csc315TermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXbw8jcMQrFQ2IZOqZLqSrEfcGgJ8Isp0',
    appId: '1:891507571778:ios:db86be7a9163d64a3401db',
    messagingSenderId: '891507571778',
    projectId: 'seahawk-explorer',
    storageBucket: 'seahawk-explorer.appspot.com',
    iosBundleId: 'com.example.csc315TermProject.RunnerTests',
  );
}
